"""持久化接口（spec §4.8）。所有跨 tick 状态必须经此接口落盘，禁止内存态。"""
from __future__ import annotations

from typing import Protocol

from ..models import CandidateModel, TaskRecord, TaskStatus


class Storage(Protocol):
    # --- 候选表 ---
    def upsert_candidate(self, candidate: CandidateModel) -> None: ...
    def pending_candidates(self) -> list[CandidateModel]: ...
    def mark_candidate_processed(self, model_id: str) -> None: ...

    # --- 任务表（唯一键 (model_id, target_gpu) 保证幂等，spec §3 不变式）---
    def insert_task(self, record: TaskRecord) -> None:
        """同 (model_id, target_gpu) 已存在活跃/成功/拉黑记录时抛 DuplicateTaskError。"""
        ...

    def update_task(self, record: TaskRecord) -> None: ...
    def tasks_by_status(self, *statuses: TaskStatus) -> list[TaskRecord]: ...
    def get_task(self, model_id: str, target_gpu: str) -> TaskRecord | None: ...

    # --- 黑名单 ---
    def is_blacklisted(self, model_id: str, target_gpu: str) -> bool: ...

    # --- GPU 覆盖率缓存（config_gen 选卡依据）---
    def gpu_coverage(self) -> dict[str, int]: ...
    def set_gpu_coverage(self, coverage: dict[str, int]) -> None: ...

    # --- 熔断开关（monitor 发现对账异常时暂停提交）---
    def kill_switch(self) -> bool: ...
    def set_kill_switch(self, on: bool, reason: str) -> None: ...

    # --- 计数器（连续失败熔断用，Task 8/9 用）---
    def get_counter(self, key: str) -> int: ...
    def set_counter(self, key: str, value: int) -> None: ...


class DuplicateTaskError(Exception):
    """违反 (model_id, target_gpu) 唯一性——防重复提交的最终防线。"""
